### ISSUE TITLE
panic of t.Log after test is complete should not mark the test as success in test.xml

### ISSUE THREAD

**Issue by xytan0056** [bazel-contrib/rules_go#3476]
### What version of rules_go are you using?

v0.37.0
### What version of gazelle are you using?

v0.29.0

### What version of Bazel are you using?

6.1.0
### Does this issue reproduce with the latest releases of all the above?
yes

### What operating system and processor architecture are you using?
darwin arm64

### Any other potentially useful information about your toolchain?

tested against go1.19.4

### What did you do?

To repo:

- `git clone -b testxml-logaftercompletion git@github.com:xytan0056/test.git`
- run `bazel test` and see the following output
### What did you see instead?
```
➜  test git:(testxml-logaftercompletion) ✗ bazel test -t- --test_env=GO_TEST_WRAP_TESTV=1 --test_output=errors ":test_test" --build_event_text_file ./test_event
...
INFO: From Testing //:test_test:
==================== Test output for //:test_test:
=== RUN   TestFunc1
=== PAUSE TestFunc1
=== CONT  TestFunc1
    main_test.go:18: log1?
--- PASS: TestFunc1 (0.00s)
PASS
panic: Log in goroutine after TestFunc1 has completed: log in go routine!


goroutine 7 [running]:
testing.(*common).logDepth(0x14000003ba0, {0x14000026090, 0x13}, 0x3)
        GOROOT/src/testing/testing.go:894 +0x3c0
testing.(*common).log(...)
        GOROOT/src/testing/testing.go:876
testing.(*common).Log(0x14000003ba0, {0x14000052fb0?, 0x0?, 0x0?})
        GOROOT/src/testing/testing.go:917 +0x4c
github.com/xytan0056/test.TestFunc1.func1()
        main_test.go:16 +0xa0
created by github.com/xytan0056/test.TestFunc1
        main_test.go:13 +0x64
================================================================================
Target //:test_test up-to-date:
  bazel-bin/test_test_/test_test
INFO: Elapsed time: 0.233s, Critical Path: 0.07s
INFO: 2 processes: 1 internal, 1 darwin-sandbox.
//:test_test                                                             FAILED in 0.1s
  /private/var/tmp/_bazel_tanx/acd964c5719399be6170cc738cf9d22f/execroot/__main__/bazel-out/darwin_arm64-fastbuild/testlogs/test_test/test.log

Executed 1 out of 1 test: 1 fails locally.
INFO: Build Event Protocol files produced successfully.
INFO: Build completed, 1 test FAILED, 2 total actions
➜  test git:(testxml-logaftercompletion) ✗ echo $?
3

```
Note that the test.log is marked `PASS`, same with test.xml file
```
➜  test git:(testxml-logaftercompletion) ✗ cat /private/var/tmp/_bazel_tanx/acd964c5719399be6170cc738cf9d22f/execroot/__main__/bazel-out/darwin_arm64-fastbuild/testlogs/test_test/test.xml
<testsuites>
        <testsuite errors="0" failures="0" skipped="0" tests="1" time="0.007" name="github.com/xytan0056/test">
                <testcase classname="test" name="TestFunc1" time="0.000"></testcase>
        </testsuite>
</testsuites>%  
```

### What did you expect to see?

same as `go test` behavior, and `"errors"` in xml should be set to non-0
```
➜  test git:(testxml-logaftercompletion) ✗ go test . -count=5 -test.v
...
PASS
panic: Log in goroutine after TestFunc1 has completed: log in go routine!


goroutine 19 [running]:
testing.(*common).logDepth(0x14000110820, {0x1400011c0a8, 0x13}, 0x3)
        /opt/homebrew/Cellar/go/1.19.4/libexec/src/testing/testing.go:894 +0x3c0
testing.(*common).log(...)
        /opt/homebrew/Cellar/go/1.19.4/libexec/src/testing/testing.go:876
testing.(*common).Log(0x14000110820, {0x14000186fb0?, 0x0?, 0x0?})
        /opt/homebrew/Cellar/go/1.19.4/libexec/src/testing/testing.go:917 +0x4c
awesomeProject.TestFunc1.func1()
        /Users/tanx/go/src/test/main_test.go:16 +0xa0
created by awesomeProject.TestFunc1
        /Users/tanx/go/src/test/main_test.go:13 +0x64
FAIL    awesomeProject  0.127s
FAIL
➜  test git:(testxml-logaftercompletion) ✗ echo $?
1
```
```
➜  test git:(testxml-logaftercompletion) ✗ go test . -count=5 -test.v -json
...
{"Time":"2023-03-10T14:41:08.11978-08:00","Action":"fail","Package":"awesomeProject","Elapsed":0.147}
➜  test git:(testxml-logaftercompletion) ✗ echo $?
1
```

**Comment by fmeum** [comment]
Not sure where to look for the root cause of the difference. Maybe https://github.com/bazelbuild/rules_go/blob/master/go/tools/bzltestutil/test2json.go is outdated compared to upstream? Do you have an idea where we should look?

**Comment by xytan0056** [comment]
rules_go [compiles the test binary then runs it](https://github.com/bazelbuild/rules_go/blob/master/go/tools/bzltestutil/wrap.go#L123-L132) with `-test.v`. Then it [relies on parsing the output prefix](https://github.com/bazelbuild/rules_go/blob/master/go/tools/bzltestutil/test2json.go#L181) to determine results to json, then to xml.

However, `go test -v` and `test_binary -test.v` behave differently. Upstream golang team seems reluctant to address this golang/go#58979. Is it possible to directly run `go test -v -json` then parse the json instead? (`test_binary` doesn't support `-test.json`)

**Comment by xytan0056** [comment]
closed by #4250 Didn't know `-test.v` accepts value
