### ISSUE TITLE
Calls to https://go.dev/dl/?mode=json are breaking airgapped builds - provide way to avoid these

### ISSUE THREAD

**Issue by peakschris** [bazel-contrib/rules_go#3945]
### What version of rules_go are you using?

0.47.1

### What version of gazelle are you using?

0.36.0

### What version of Bazel are you using?

7.2.0rc1

### Does this issue reproduce with the latest releases of all the above?

Yes

### What operating system and processor architecture are you using?

Windows

### Any other potentially useful information about your toolchain?

N/a

### What did you do?

Attempting to run bazel build from airgapped environment, the build fails unable to connect to https://go.dev/dl/?mode=json&include=all. We have created some mirrors for github.com, dl.google.com, etc on our internal artifactory, but artifactory will not mirror this URL as it uses a query.

I would like some way to input the required information into the use of rules_go in our MODULE.bazel file, and avoid the need for rules_go to make this request. I see in the code that a parameter named sdks can be used to avoid this request, but I can't see how to provide it in a module-based build.

An alternative would be to allow this URL to be overridden in the module file; then I could download this file and vendor it as versions.json

**Comment by peakschris** [comment]
This is where the request is made: https://github.com/bazelbuild/rules_go/blob/e7ddb9ea474e6b5137dfc074f913529df80d7e5c/go/private/sdk.bzl#L75

**Comment by fmeum** [comment]
This is an interesting problem that I think can be solved by introducing an intermediate extension that records the extracted information in the `MODULE.bazel.lock` file. I'll give this some more thought and try to implement it.

**Comment by peakschris** [comment]
@fmeum thank you for looking at this! For us, we cannot source manage MODULE.bazel.lock because we don't use git and the unsupported merge of this huge file (it is 2MB for us) will be incorrect more often than not. So a solution involving direct specification of the inputs in MODULE.bazel or in a separate file would be much better

**Comment by fmeum** [comment]
@peakschris When you say "don't use Git", what are you using instead and why does that prevent you from checking in MODULE.bazel.lock? Bazel 7.2.0rc1 comes with a revised lockfile format that is much more VCS friendly and less verbose.

Generally speaking, I would like to first find a general solution that works out of the box, but I'm sure we'll find a way to support your use case.

**Comment by peakschris** [comment]
@fmeum we use a custom VCS layer, with perforce as the backend. The VCS layer was written years ago and is in maintenance mode now, so it's practically impossible to get significant changes made. It does not support custom merge drivers.

We also have a significant problem with contentious files that cause 'MR's to back up in our test pipeline. MODULE.bazel.lock would be a massively contentious file.

So there are two issues:
1) MODULE.bazel.lock can't be auto-merged in our system and will be broken often. I can't give a tool to developers to use manually as some merge steps happen in CI via a web UI.
2) MODULE.bazel.lock would cause MRs to queue up and retest. We don't have a good merge train like github.

I'm sure this will be an issue for others too, who have similar constraints. I don't have these issues with rules_js, etc, and I like their approach of providing the inputs to the toolchain in the MODULE.bazel file. 

We can split up MODULE.bazel via include statements that allow different elements of the build to be specified in smaller files that are not contentious and are obvious to merge graphically.

Thanks again for thinking about this

**Comment by peakschris** [comment]
I've actually stumbled on a way to avoid these queries:

```
bazel_dep(name = "rules_go", version = "0.47.1")
go_sdk = use_extension("@rules_go//go:extensions.bzl", "go_sdk")
go_sdk.download(
    version = "1.22.3",
    # explicitly specify SDK names/checksums to avoid a query which fails in airgapped builds
    # get checksums from https://go.dev/dl/?mode=json&include=all
    sdks = {
        "linux_amd64": ("go1.22.3.linux-amd64.tar.gz", "8920ea521bad8f6b7bc377b4824982e011c19af27df88a815e3586ea895f1b36"),
        "windows_arm64": ("go.1.22.3.windows-arm64.tar.gz", "59b76ee22b9b1c3afbf7f50e3cb4edb954d6c0d25e5e029ab5483a6804d61e71"),
    },
)
```

Would it be possible to update documentation (https://github.com/bazelbuild/rules_go/blob/master/go/toolchains.rst#go_download_sdk) to include examples of use with Modules? This is what I was missing.

**Comment by fpotter** [comment]
Thanks for the tip, @peakschris!

Building on yours, I'm using the following curl + jq command to dump output we can copy/paste into our MODULE.bazel file.

This command ...

```sh
curl -s https://go.dev/dl/\?mode\=json\&include\=all | jq -r '.[] | select(.version == "go1.19.13") | .files | .[] | select(.kind == "archive" and (.os == "linux" or .os == "darwin") and (.arch == "arm64" or .arch == "amd64") ) | "\"\(.os)_\(.arch)\": (\"\(.filename)\", \"\(.sha256)\")" '
```

... will produce this output you can copy/paste into `sdks = { ... }` ....

```
"darwin_amd64": ("go1.19.13.darwin-amd64.tar.gz", "1b4329dc9e73def7f894ca71fce78bb9f3f5c4c8671b6c7e4f363a3f47e88325")
"darwin_arm64": ("go1.19.13.darwin-arm64.tar.gz", "022b35fa9c79b9457fa4a14fd9c4cf5f8ea315a8f2e3b3cd949fea55e11a7d7b")
"linux_amd64": ("go1.19.13.linux-amd64.tar.gz", "4643d4c29c55f53fa0349367d7f1bb5ca554ea6ef528c146825b0f8464e2e668")
"linux_arm64": ("go1.19.13.linux-arm64.tar.gz", "1142ada7bba786d299812b23edd446761a54efbbcde346c2f0bc69ca6a007b58")
```

**Comment by eightseventhreethree** [comment]
A dependency free Python version:

```python
#!/usr/bin/env python3

import urllib.request
import json
import sys


def main():
    if len(sys.argv) != 2:
        print("Usage: main.py <go_version>")
        print("Example: main.py 1.24.2")
        sys.exit(1)

    semver = sys.argv[1]
    url = "https://go.dev/dl/?mode=json&include=all"
    version = "go" + semver

    try:
        with urllib.request.urlopen(url) as response:
            data = json.loads(response.read().decode())
    except Exception as e:
        print(f"Error fetching or parsing data: {e}")
        sys.exit(1)

    files_by_platform = {}

    for entry in data:
        if entry.get("version") == version:
            for file in entry.get("files", []):
                if (
                    file.get("kind") == "archive"
                    and file.get("os") in ("linux", "darwin")
                    and file.get("arch") in ("arm64", "amd64")
                ):
                    key = f'{file["os"]}_{file["arch"]}'
                    files_by_platform[key] = (file["filename"], file["sha256"])
            break

    if not files_by_platform:
        print(f"Version '{version}' not found in the Go releases list.")
        sys.exit(1)

    print("go_sdk.download(")
    print(f'    version = "{semver}",')
    print("    sdks = {")
    for platform, (filename, sha256) in sorted(files_by_platform.items()):
        print(f'        "{platform}": ("{filename}", "{sha256}"),')
    print("    },")
    print(")")


if __name__ == "__main__":
    main()
```

Then upgrades are simply calling the py_binary target and copy stdout:
```bash
bazel run  //python/target_name:bin -- 1.24.2
```

**Comment by eightseventhreethree** [comment]
The change in https://github.com/bazel-contrib/rules_go/pull/4393 seems to have caused a regression where the explicit definition of the SDK still makes a call to go.dev. This domain is is being rewritten in Bazel downloader to point to an Artifactory instance, but Artifactory ignores the json param and serves an html page leading to this error:
```
ERROR: /home/runner/.bazel/external/rules_go~/go/private/sdk.bzl:560:23: Traceback (most recent call last):
	File "/home/runner/.bazel/external/rules_go~/go/private/extensions.bzl", line 268, column 26, in _go_sdk_impl
		_download_sdk(
	File "/home/runner/.bazel/external/rules_go~/go/private/extensions.bzl", line 431, column 57, in _download_sdk
		sdks_by_version.update(fetch_sdks_by_version(module_ctx))
	File "/home/runner/.bazel/external/rules_go~/go/private/sdk.bzl", line 586, column 32, in fetch_sdks_by_version
		return _parse_versions_json(data)
	File "/home/runner/.bazel/external/rules_go~/go/private/sdk.bzl", line 560, column 23, in _parse_versions_json
		sdks = json.decode(data)
Error in decode: at offset 0, unexpected character "<"
ERROR: error evaluating module extension go_sdk in @@rules_go~//go:extensions.bzl
```

Is there a way to prevent the external call to go.dev?

cc: @fmeum

**Comment by fmeum** [comment]
@eightseventhreethree This is definitely supporting since I thought we only moved the download logic from the repo rule to the extension. On previous versions, are you able to tell how the download made in the repo rules was able to pass through your cache?

Edit: Possibly nvm - are you saying that you already set `sdk_by_version`?

**Comment by eightseventhreethree** [comment]
@fmeum yes, I have the explicit definition like so:
```
go_sdk.download(
    sdks = {
        "darwin_amd64": ("go1.24.6.darwin-amd64.tar.gz", "4a8d7a32052f223e71faab424a69430455b27b3fff5f4e651f9d97c3e51a8746"),
        "darwin_arm64": ("go1.24.6.darwin-arm64.tar.gz", "4e29202c49573b953be7cc3500e1f8d9e66ddd12faa8cf0939a4951411e09a2a"),
        "linux_amd64": ("go1.24.6.linux-amd64.tar.gz", "bbca37cc395c974ffa4893ee35819ad23ebb27426df87af92e93a9ec66ef8712"),
        "linux_arm64": ("go1.24.6.linux-arm64.tar.gz", "124ea6033a8bf98aa9fbab53e58d134905262d45a022af3a90b73320f3c3afd5"),
    },
    version = "1.24.6",
)
```

Previously this definition was all that was needed to bypass the call to go.dev, now it's making the call regardless and for the reasons mentioned above with limitations of Artifactory proxying json isn't being returned. Thanks for looking into this.

**Comment by fmeum** [comment]
The downloads are triggered for the default Go toolchain registered by `rules_go`. Before the PR, this would only happen if that toolchain was actually selected. 

Unfortunately the Bazel change required to enable fully airgapped builds won't make it into 8.4.0. I need to think about what to do - we may have to roll back the change for now.

**Comment by midnightconman** [comment]
I have this issue with version `0.56.1` also 😿

**Comment by scasagrande** [comment]
I just encountered this same issue while redirecting my last new dependencies to artifactory. Reverted to 0.55.1 for now.

**Comment by eightseventhreethree** [comment]
@fmeum is reverting the change in the near timeline?

**Comment by fmeum** [comment]
The PR has been reverted on master and we can look into creating a patch release.

**Comment by fmeum** [comment]
The PR has been reverted on master and we can look into creating a patch release.

**Comment by eightseventhreethree** [comment]
Revert made it into:

https://github.com/bazel-contrib/rules_go/releases/tag/v0.58.0

Edit: [Issue with BCR release](https://github.com/bazel-contrib/rules_go/issues/4487)

Thanks @fmeum

**Comment by fmeum** [comment]
Could you test https://github.com/bazel-contrib/rules_go/pull/4493, which is a reland that handles airgapped builds as well as Artifactory mirrors?

**Comment by eightseventhreethree** [comment]
@fmeum I can test, but I'm unfamiliar on how to use that ref if it's not published on BCR. If you have a guide pointer or what override I need to use more than happy to test and report back.

**Comment by fmeum** [comment]
@eightseventhreethree You can use `git_override`:

```starlark
bazel_dep(name = "rules_go")
git_override(
    module_name = "rules_go",
    remote = "https://github.com/bazel-contrib/rules_go",
    branch = "reintroduce-facts",
)
```

**Comment by eightseventhreethree** [comment]
@fmeum tested w/ and it worked in our CI:
```python
bazel_dep(name = "rules_go")
git_override(
    module_name = "rules_go",
    commit = "fa5900262a9dd099ec018043dafb4d4ab42735bb",
    remote = "https://github.com/bazel-contrib/rules_go",
)
```
