### ISSUE TITLE
Binary that depends on `cloudflare/circl` can't be built cross-platform

### ISSUE THREAD

**Issue by aaomidi** [bazel-contrib/rules_go#4154]
### What version of rules_go are you using?
0.50.1

### What version of gazelle are you using?
0.39.1

### What version of Bazel are you using?
7.4.0

### Does this issue reproduce with the latest releases of all the above?
Yes

### What operating system and processor architecture are you using?
Darwin ARM64

### Any other potentially useful information about your toolchain?
This is related to the infamous `circl` dependency.

### What did you do?
I have a go_binary that through a long list of dependencies ends up depending on `circl`. I do get circl from the BCR: 

```
bazel_dep(
    name = "circl",
    version = "1.3.8",
)
```

My binary rule is defined as such:

```
go_binary(
    name = "api",
    embed = [":api_lib"],
    gotags = ["purego"],
    pure = "on",
)
```

I try to build it like:

```
bazel build //control-plane/api --platforms=@rules_go//go/toolchain:linux_arm64
```

My error:
```
ERROR: /private/var/tmp/_bazel_amir/3dbd0b78d662a8a6e641b2d6e1f7442e/external/bazel_tools/tools/cpp/BUILD:58:19: in cc_toolchain_alias rule @@bazel_tools//tools/cpp:current_cc_toolchain: 
Traceback (most recent call last):
        File "/virtual_builtins_bzl/common/cc/cc_toolchain_alias.bzl", line 26, column 48, in _impl
        File "/virtual_builtins_bzl/common/cc/cc_helper.bzl", line 225, column 17, in _find_cpp_toolchain
Error in fail: Unable to find a CC toolchain using toolchain resolution. Target: @@bazel_tools//tools/cpp:current_cc_toolchain, Platform: @@rules_go~//go/toolchain:linux_arm64, Exec platform: @@bazel_tools//tools:host_platform
ERROR: /private/var/tmp/_bazel_amir/3dbd0b78d662a8a6e641b2d6e1f7442e/external/bazel_tools/tools/cpp/BUILD:58:19: Analysis of target '@@bazel_tools//tools/cpp:current_cc_toolchain' failed
```

### What did you expect to see?
I expected this build to not need the C++ toolchain.

### What did you see instead?
An error for C++ toolchain.

**Comment by fmeum** [comment]
Please test whether https://github.com/bazel-contrib/rules_go/commit/87e66bb70858570ac668f95662d6070417d5a416 fixes this for you.

**Comment by aaomidi** [comment]
I've added

```
git_override(
    module_name = "rules_go",
    commit = "87e66bb70858570ac668f95662d6070417d5a416",
    remote = "https://github.com/bazel-contrib/rules_go.git",
)
```

And unfortunately 

```
bazel build //control-plane/api --platforms=@rules_go//go/toolchain:linux_arm64


ERROR: /private/var/tmp/_bazel_amir/3dbd0b78d662a8a6e641b2d6e1f7442e/external/bazel_tools/tools/cpp/BUILD:58:19: in cc_toolchain_alias rule @@bazel_tools//tools/cpp:current_cc_toolchain: 
Traceback (most recent call last):
        File "/virtual_builtins_bzl/common/cc/cc_toolchain_alias.bzl", line 26, column 48, in _impl
        File "/virtual_builtins_bzl/common/cc/cc_helper.bzl", line 225, column 17, in _find_cpp_toolchain
Error in fail: Unable to find a CC toolchain using toolchain resolution. Target: @@bazel_tools//tools/cpp:current_cc_toolchain, Platform: @@rules_go~//go/toolchain:linux_arm64, Exec platform: @@bazel_tools//tools:host_platform
ERROR: /private/var/tmp/_bazel_amir/3dbd0b78d662a8a6e641b2d6e1f7442e/external/bazel_tools/tools/cpp/BUILD:58:19: Analysis of target '@@bazel_tools//tools/cpp:current_cc_toolchain' failed
```

Fails

**Comment by aaomidi** [comment]
This might be a significantly simpler repro.

```
bazel build --repo_env=BAZEL_DO_NOT_DETECT_CPP_TOOLCHAIN=1 --@rules_go//go/config:pure=true  @circl//dh/x448:x448 
```

**Comment by aaomidi** [comment]
```
bazel query "somepath(//control-plane/api, @rules_go//:cgo_context_data)"
```

```
//control-plane/api:api
@rules_go//:go_context_data
@rules_go//:cgo_context_data
```

**Comment by sallustfire** [comment]
> ```
> bazel query "somepath(//control-plane/api, @rules_go//:cgo_context_data)"
> ```
> 
> ```
> //control-plane/api:api
> @rules_go//:go_context_data
> @rules_go//:cgo_context_data
> ```

What about if you try cquery? `@rules_go//:go_context_data` does depend on `@rules_go//:cgo_context_data` depending on transitions.

**Comment by aaomidi** [comment]
Heh interesting..

```
//control-plane/api:api (92fba1e)
@rules_go//:go_context_data (8754af7)
@@rules_go~~go_sdk~io_bazel_rules_nogo//:nogo (4bda251)
//ci/analyzers:limited_nogo (4bda251)
//ci/analyzers:limited_nogo_actual (da2a0f7)
@rules_go//:stdlib (f0a298a)
@rules_go//:cgo_context_data (f0a298a)
```

I disabled `nogo` and after that cquery returns empty.

However, even after removing nogo:

```
bazel build --repo_env=BAZEL_DO_NOT_DETECT_CPP_TOOLCHAIN=1 --@rules_go//go/config:pure=true @circl//dh/x448:x448
```

Fails to build

```
ERROR: /private/var/tmp/_bazel_amir/3dbd0b78d662a8a6e641b2d6e1f7442e/external/bazel_tools/tools/cpp/BUILD:58:19: in cc_toolchain_alias rule @@bazel_tools//tools/cpp:current_cc_toolchain: 
Traceback (most recent call last):
        File "/virtual_builtins_bzl/common/cc/cc_toolchain_alias.bzl", line 26, column 48, in _impl
        File "/virtual_builtins_bzl/common/cc/cc_helper.bzl", line 225, column 17, in _find_cpp_toolchain
Error in fail: Unable to find a CC toolchain using toolchain resolution. Target: @@bazel_tools//tools/cpp:current_cc_toolchain, Platform: @@bazel_tools//tools:host_platform, Exec platform: @@bazel_tools//tools:host_platform
ERROR: /private/var/tmp/_bazel_amir/3dbd0b78d662a8a6e641b2d6e1f7442e/external/bazel_tools/tools/cpp/BUILD:58:19: Analysis of target '@@bazel_tools//tools/cpp:current_cc_toolchain' failed
INFO: Analyzed target @@circl~//dh/x448:x448 (8 packages loaded, 4748 targets configured).
WARNING: errors encountered while analyzing target '@@circl~//dh/x448:x448', it will not be built.
````

And unfortunately I can't run:

```
bazel cquery --@rules_go//go/config:pure=true --repo_env=BAZEL_DO_NOT_DETECT_CPP_TOOLCHAIN=1  "somepath(@circl//dh/x448:x448, @rules_go//:cgo_context_data)"
```

To see why this is happening since it fails with that same error.

**Comment by aaomidi** [comment]
So, I've added a bunch of patches on top of the circl dependency. Specifically, they remove the select statement in deps. E.g.:

```
--- dh/x448/BUILD.bazel
+++ dh/x448/BUILD.bazel
@@ -19,12 +19,7 @@
     visibility = ["//visibility:public"],
     deps = [
         "//math/fp448",
-    ] + select({
-        "@rules_go//go/platform:amd64": [
-            "@org_golang_x_sys//cpu:go_default_library",
-        ],
-        "//conditions:default": [],
-    }),
+    ],
 )
 ```
 
 And, they remove the cdeps statement:
 
 ```
 --- dh/x448/BUILD.bazel
+++ dh/x448/BUILD.bazel
@@ -14,7 +14,6 @@
         "table.go",
     ],
     cgo = True,
-    cdeps = ["//math/fp448:header"],
     importpath = "github.com/cloudflare/circl/dh/x448",
     visibility = ["//visibility:public"],
     deps = [

```

With these changes, I'm getting it closer and closer to working. I think whats happening is that unfortunately `cgo = True` in the dependency is forcing the go toolchain to look for C++ toolchain.

Any help to figure out how to fix this would be appreciated

**Comment by aaomidi** [comment]
I tried a different strategy. In this strategy I do not use `circl` from BCR and instead:

```
go_deps.gazelle_override(
    directives = [
        "gazelle:build_tags purego",
        "gazelle:exclude **/*_amd64*",
    ],
    path = "github.com/cloudflare/circl",
)
```
This allows me to build the go_binary target below:

```
go_library(
    name = "api_lib",
    srcs = ["main.go"],
    importpath = "github.com/spirl/spirl/control-plane/api",
    deps = ["//control-plane/api/cmd"],
)

go_binary(
    name = "api",
    embed = [":api_lib"],
    gotags = ["purego"],
    pure = "on",  # No CGO
    x_defs = {
        "github.com/spirl/spirl/common/version.version": "${STABLE_VERSION}",
    },
)

```

However. It does not allow me to build the api_lib target.

**Comment by dzbarsky** [comment]
Perhaps you could use with_cfg to transition your binary? That way you can set gotags on it from build.bazel instead of affecting everything from CLI?

**Comment by fardream** [comment]
I am running into similar problems. it look like remove the `_lib` and directly add the source codes and deps to `go_ binary` will work

```starlark
go_binary(
    name = "api",
    srcs = ["main.go"],
    deps = ["//control-plane/api/cmd"],
    gotags = ["purego"],
    pure = "on",  # No CGO
    x_defs = {
        "github.com/spirl/spirl/common/version.version": "${STABLE_VERSION}",
    },
)
```

looks like `gotags` are not properly passed to `embed`?

**Comment by albertocavalcante** [comment]
Linking to this issue: https://github.com/cloudflare/circl/issues/537#issuecomment-2738664357
