### ISSUE TITLE
rules_go should load rules_shell targets explicitly

### ISSUE THREAD

**Issue by criemen** [bazel-contrib/rules_go#4193]
I'm using bazel 8.0.0 with the latest rules_go, and I have `common --incompatible_autoload_externally="+@rules_java"` in my `.bazelrc`.
This doesn't seem to be compatible with 0.50.1 of rules_go, as I get

```
ERROR: Traceback (most recent call last):
        File "/private/var/tmp/_bazel_criemen/47b2da4b7ff4a00c3a91bcb9cb5596ee/external/rules_go+/BUILD.bazel", line 148, column 18, in <toplevel>
                lines_sorted_test(
        File "/private/var/tmp/_bazel_criemen/47b2da4b7ff4a00c3a91bcb9cb5596ee/external/rules_go+/go/private/tools/lines_sorted_test.bzl", line 39, column 21, in lines_sorted_test
                files_equal_test(
        File "/private/var/tmp/_bazel_criemen/47b2da4b7ff4a00c3a91bcb9cb5596ee/external/rules_go+/go/private/tools/files_equal_test.bzl", line 108, column 11, in files_equal_test
                native.sh_test(
Error: no native function or rule 'sh_test'
```

**Comment by fmeum** [comment]
You can use 0.51.0-rc2, but leaving the value of that at its default in Bazel 8 should also work.

**Comment by criemen** [comment]
Ah, I hadn't seen that, but as rules_rust has the same problem, I'll just wait for a stable release. We initially started setting that flag to workaround https://github.com/bazelbuild/bazel/issues/23929.
